# Site settings
title: Sim칩n Pati침o
author: Sim칩n Pati침o
description: Computer science - Aerospace engineering. Specialized in programming, numerical methods, and Industry 4.0 technologies.
url: "https://simonpatino.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Exclude files from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
